### PR TITLE
[lint] Remove unnecessary semicolons

### PR DESCRIPTION
**Pull request by dayo09**
This commit removes unnecessary semicolons.

ONE-vscode-DCO-1.0-Signed-off-by: dayo09 <dayoung.lee@samsung.com>

---

For #1253

### CODE REVIEW

**Review by yunjayh — APPROVED** [review]
LGTM

**Comment by hyunsik-yoon** [comment]
In C++ we put semicolon at the end of class declaration. I wonder the reason why we need to remove semicolon after class declaration in TS.

**Comment by dayo09** [comment]
@hyunsik-yoon It's a redundant semicolon for TS language. Therefore, eslint gives an error. 

https://eslint.org/docs/latest/rules/no-extra-semi

I referred eslint rules, you may also be able to find typescript grammars :-D

**Comment by dayo09** [comment]
NOTE: This is done with eslint --fix option, as unncessary semicolon error is almost the only fixable by that. :-D

**Comment by hyunsik-yoon** [comment]
> Therefore, eslint gives an error.
...
> you may also be able to find this in typescript language specification, too 

The following lines in TS are all valid and work: ([link](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD29oG8C+1oHpPQHZIgFMBbAS2HhHlwFgAoC3CSwgOioHMAKAcgDNEPAJQZseAiXKVq0AC6J6oSDABCYAE4pUAblE4iZClVoNqzEG068ARhuG6sOfNANTjchXSA))

```ts
class Foo {}  // 1. no semicolon
console.log('foo')  // 2. no semicolon too
class Foo {};  // 3. semicolon
console.log('foo');  // 4. no semicolon too
```

I am personally not against this PR. :-)

I just want to know any proof to approve this PR. 

Maybe providing some reference URL or screen capture of error from eslint could be good evidence to persuade other people who need to review.

**Comment by dayo09** [comment]
@hyunsik-yoon 
It removes not only the semicolons at the end of class definition but the floating (literally unused) semicolons.
Here, it removes semicolons just because they are 'redundant'.

(plus, As far as I know, javascript's function does not need to end with ';' but it's recommended to put semicolons.)

The playground doesn't emit every warnings as eslint does.  Naturally, eslint does more strict checking. For example, it doesn't emit any error on every whitespace but we run 'clang-format' to remove them..

Eslint offers us a 'recommended' checker option. When it's turned on, 'unused semicolon' option is on.
I think it's has the same quality as we remove redundant white spaces.

**Comment by hyunsik-yoon** [comment]
I think that sometimes providing useful links could give more objective view.
So I tried to find why `;` after class in C++ is useful and https://stackoverflow.com/questions/1783465/why-must-i-put-a-semicolon-at-the-end-of-class-declaration-in-c mentioned that `;` is very useful in C++. However, grammar in TS is different from C++ and I now also think that `;` after TS class seems redundant.

**Review by hyunsik-yoon — APPROVED** [review]

**Comment by llFreetimell** [comment]
@dayo09 @hyunsik-yoon 

At first, I had same thoughts with @hyunsik-yoon, which is "why we should remove those semicolons? is there any official guide for this?"
In the point of view, https://eslint.org/docs/latest/rules/no-extra-semi seems to be about "style", not "guide".

But I could find https://www.typescriptlang.org/docs/handbook/2/classes.html and the official example is following current PR's policy.
So now I think we can merge this PR with confidence :)

**Pull request merged**
