### PR TITLE
[OneExplorer] Add delete shortcut

### PR DESCRIPTION
**Pull request by dayo09**
This commit adds delete shortcut.

ONE-vscode-DCO-1.0-Signed-off-by: Dayoung Lee <dayoung.lee@samsung.com>

### CODE REVIEW

**Review by jyoungyun — APPROVED** [review]
LGTM

**Comment by dayo09** [comment]
@Samsung/one-vscode_committers PTAL :-D

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
All test has finished by UI is still showing it's running.
I think it's OK to land.

**Pull request merged**
