### PR TITLE
[Utils] Move MultiStepInput out of external dir

### PR DESCRIPTION
**Pull request by jyoungyun**
This commit moves MultiStepInput class out of external dir.
This commit contains the code chage about MultiStepInput.

ONE-vscode-DCO-1.0-Signed-off-by: Jiyoung Yun <jy910.yun@samsung.com>

Draft PR: #699 (Big draft PR...)

### CODE REVIEW

**Review by llFreetimell — APPROVED** [review]
LGTM

**Comment by yunjayh** [comment]
Where can I find the background of introducing new directory, `external` in `utils`? Itself looks good, but I couldn't remember any history about this pr. :pray:

**Comment by jyoungyun** [comment]
/cc @yunjayh You can find the history about `utils` directory [here](https://github.com/Samsung/ONE-vscode/commits/main/src/Utils/external).

@llFreetimell introduces `external` directory for managing files copied from external source code.
Related PR: https://github.com/Samsung/ONE-vscode/commit/f64c0b34f1d5e87063d13b720164746ae3f56365

**Review by yunjayh — APPROVED** [review]
LGTM Thank you 😄

**Review by YongseopKim — APPROVED** [review]

**Pull request merged**
