### PR TITLE
[infra] Add license-checker package

### PR DESCRIPTION
**Pull request by llFreetimell**
To enable license checker in Github Action,
`license-checker` package is needed.

ONE-vscode-DCO-1.0-Signed-off-by: Seok NamKoong <seok9311@naver.com>

---

Parent Issue : #285 
Draft : #288

### CODE REVIEW

**Review by YongseopKim — APPROVED** [review]
LGTM

**Comment by hyunsik-yoon** [comment]
@llFreetimell 
I guess that package.json and package-lock.json will be used make `vsix` file and will be delivered to end-user.
For this reason, I realized that putting githubAction-related packages into package.json and package-lock.json might not be correct.

**Comment by llFreetimell** [comment]
@hyunsik-yoon 

As I am not good at node.js, please let me know if I am wrong :)

> package.json and package-lock.json will be used make vsix file and will be delivered to end-user.

I think this is `dependencies`, not `devDependencies` :)
(https://stackoverflow.com/questions/18875674/whats-the-difference-between-dependencies-devdependencies-and-peerdependencies)

>  putting githubAction-related packages into package.json and package-lock.json might not be correct...

I don't know why all the packages are included in `devDependencies`, but I think following steps would resolve this :D

- Separate `dependencies` and `devDependencies` according to judgment whether a package is mandatory for production level or not
- Put Github Action related packages to `devDependencies`

**Comment by hyunsik-yoon** [comment]
`devDependency`! 😹 I didn't know that `devDependency` has such behavior. 
Thanks. All concerns were resolved. 👍

**Review by hyunsik-yoon — APPROVED** [review]

**Pull request merged**
