### PR TITLE
[Circletracer] Set clang-format for external folder

### PR DESCRIPTION
**Pull request by CODe1995**
Set clang-format for external folder and no longer fix that warning.

ONE-vscode-DCO-1.0-Signed-off-by: Seunghyun Kang <code.57x53@gmail.com>

### CODE REVIEW

**Comment by CODe1995** [comment]
from comment([#221 comment](https://github.com/Samsung/ONE-vscode/pull/221#issuecomment-931907653))

**Comment by llFreetimell** [comment]
Please revise the commit msg and title.
`external` directory can include another files in the future and this PR does not include any related things for minjs :)

**Comment by CODe1995** [comment]
Thank you. Anything more to edit?

**Review by llFreetimell — APPROVED** [review]
LGTM

**Review by yesfordev — APPROVED** [review]
LGTM

**Pull request merged**
