### PR TITLE
[infra] Update flowchart of license checker

### PR DESCRIPTION
**Pull request by llFreetimell**
This commit updates license checker flowchart with mermaid format
because png file is not updated well on git.

ONE-vscode-DCO-1.0-Signed-off-by: Seok NamKoong <seok9311@naver.com>

---

Parent Issue : #356

### CODE REVIEW

**Comment by mhs4670go** [comment]
Can the color inside the box be changed? The messages are hard to see with dark mode.

**Comment by llFreetimell** [comment]
Maybe possible..! Which color would be better? :D white?

**Comment by mhs4670go** [comment]
@llFreetimell How about black letter? Black letter in the white box.

**Comment by llFreetimell** [comment]
Ah... white mode is problem for now -_-... I will find proper colors..!

**Comment by llFreetimell** [comment]
@mhs4670go PTAL :D

**Review by mhs4670go — APPROVED** [review]
Seems better:)

**Comment by hyunsik-yoon** [comment]
Is there any manual work?
I guess `Add package information to package-judgment.json` seems to be manual work.
Could you explicitly mention such work as manual work (not by CI)?

**Comment by llFreetimell** [comment]
Parallelogram is "manual work" but you want to see explicit description, am I right? :)

**Review by mhs4670go — APPROVED** [review]

**Review by hyunsik-yoon — APPROVED** [review]
LGTM

**Pull request merged**
