### PR TITLE
[MPQEditor] Handle invalid VISQ data

### PR DESCRIPTION
**Pull request by stamalakhov**
This commit implements handling of invalid VISQ file.

It's correctness is approved below:

https://github.com/Samsung/ONE-vscode/assets/112689352/d5405007-5db1-4fe4-aa91-5ad93be43ce4

Fresh draft: https://github.com/Samsung/ONE-vscode/pull/1543
Full draft: https://github.com/Samsung/ONE-vscode/pull/1505
Related: https://github.com/Samsung/ONE-vscode/issues/1491

ONE-vscode-DCO-1.0-Signed-off-by: s.malakhov <s.malakhov@partner.samsung.com>

### CODE REVIEW

**Review by dayo09 — APPROVED** [review]
LGTM Thanks.
However, additionally, I think it would be better if
(1) non-visq files are unabled to be selected from the window initially.
(2) the circle viewer doesn't flick.

And I wonder what would happen if any non-visq file with *.visq.json postfix is selected.

**Comment by stamalakhov** [comment]
@dayo09 Thank you for your review.
> non-visq files are unabled to be selected from the window initially.

By default selector is  set to `target files`, which are `*.visq.json`.



> the circle viewer doesn't flick.

It will cost a more effort and much edits on non `MPQEditor` part.



> And I wonder what would happen if any non-visq file with *.visq.json postfix is selected.

It will make sure that file doesn't contain `error` section or `meta` section, and will reboot in `selector` mode.
Please see https://github.com/Samsung/ONE-vscode/blob/1295a7436b7d78e6972f87c0d6e71d172034db53/src/MPQEditor/MPQCircleSelector.ts#L253

**Comment by dayo09** [comment]
@stamalakhov I don't mind whether you proceed it in next PR or here. :-D

**Comment by stamalakhov** [comment]
@dayo09 
I've reworked PR. No flickering now.

**Review by jyoungyun — APPROVED** [review]
LGTM

**Pull request merged**
