### PR TITLE
Use Logger for views

### PR DESCRIPTION
**Pull request by hyunsik-yoon**
This replaces console.log to Logger among source files for views.

for #662

ONE-vscode-DCO-1.0-Signed-off-by: Hyun Sik Yoon <hyunsik.yoon.1024@gmail.com>

### CODE REVIEW

**Comment by yunjayh** [comment]
First of all, I haven't studied how to do great code review.. If this review is inappropriate way to review the codes and pr, please let me know. 😓 

Q) Are you going to replace every `console.log()` to `Logger.Info()`, not using `Logger.Debug()`? 

IMHO some of the `console.log()` feels better to be replaced with `Logger.Debug()`. Of course, the code authors are the only person who knows the intention, so how about requesting the code author as reviewer (for this pr, it will be @ dayo09 @ jyoungyun )?

**Comment by hyunsik-yoon** [comment]
@yunjayh 

> Q) Are you going to replace every console.log() to Logger.Info(), not using Logger.Debug()?

Well, I sometimes replace some into `debug()`.  (for example, [this one](https://github.com/Samsung/ONE-vscode/pull/742/files#diff-c4e239a4ac6e81d021b1550552dc873eff1a6be2fdeb0f13aa8b5beae3661484R31).)

`Debug()` log will not be shown in final release.
and others such as `info`, `error`, and `warning` will be shown in final release....
After release, user will capture logs when they ask some questions and I think the log needs to have sufficient information to track how the user uses our extension. For such log, I mark the log as `info`.  :-)

I am not sure I have to ask authors to review this PR because I think changing console.log to log seems trivial changes...

**Comment by yunjayh** [comment]
> I am not sure I have to ask authors to review this PR because I think changing console.log to log seems trivial changes. :-)

:+1: Thank you for answering the question! The changes looks good to me :smile:

**Review by yunjayh — APPROVED** [review]

**Review by llFreetimell — APPROVED** [review]
LGTM

**Pull request merged**
