### PR TITLE
[CfgEditor] Add Quantize Step UI

### PR DESCRIPTION
**Pull request by llFreetimell**
This commit adds Quantize Step UI.

ONE-vscode-DCO-1.0-Signed-off-by: Seok NamKoong <seok9311@naver.com>

---

Parent Issue : #563

---

#### Before & After

| Type | Item | Before | After |
| :---: | :---: | :---: | :---: |
| UI | Quantize Tab | :x: NYI | quantize |

### CODE REVIEW

**Review by jyoungyun — APPROVED** [review]
LGTM

**Review by YongseopKim — APPROVED** [review]
LGTM

**Comment by jinevening** [comment]
The UI looks very good to me. I'd like to say just a few things.

1. Mode: Why `moving_average` mode was removed?
2. Input Type, Output Type: It would be better to explain what `default` means. For example `default (same with quantized data type)` or a question mark like the one next to TF_Style_Maxpool.
3. Advanced Options: What kind of options come here? I think `mode` (and `min_percentile`, `max_percentile`) can come here. Those options are not adjusted in most cases.
4. Quantization Config File: It would be better to explain what is the role of config file. For example `Quantization Config File (for mixed-precision quantization)` or a question mark.
5. Input Model Data Type: It has only one option (float32), so I think this can be removed.
6. Input Data: It would be better to explain what is the role of input data. For example, using a question mark. `Input Data (?)` If cursor is placed on the question mark, the explanation may pop up like `Dataset used to quantize activation. If not given, random data will be used for quantization, which will seriously degrade the accuracy of the model.`
7. Input Data Format: It would be better to add explanation of each format. Maybe using question marks or external links.

**Comment by llFreetimell** [comment]
> Mode: Why moving_average mode was removed?

My mistake :crying_cat_face: 

> Input Type, Output Type: It would be better to explain what default means. For example default (same with quantized data type) or a question mark like the one next to TF_Style_Maxpool.

I changed `default` to `quantized data type` :)

> Advanced Options: What kind of options come here? I think mode (and min_percentile, max_percentile) can come here. Those options are not adjusted in most cases.

My intention is following :)

- Basic options : Mandatory/strongly required options. Options which are directly related with quantization.
- Advanced options : Usually not used options. Not important options. Options which are not related with quantization.

So I put `mode` at basic options.
However, it is not that often used, I will move it to Advanced Options!
(I didn't notice that `min_percentile` and `max_percentile` are only used for `percentile`..!)

> Quantization Config File: It would be better to explain what is the role of config file. For example Quantization Config File (for mixed-precision quantization) or a question mark.

Added question mark :D

> Input Model Data Type: It has only one option (float32), so I think this can be removed.

If there will be only one option(float32) in the future, removing would be better.
However, if it is not that sure, I think leaving as it is seems not that bad :)

> Input Data: It would be better to explain what is the role of input data. For example, using a question mark. Input Data (?) If cursor is placed on the question mark, the explanation may pop up like Dataset used to quantize activation. If not given, random data will be used for quantization, which will seriously degrade the accuracy of the model.

Added question mark :D
FYI, all of question marks in the editor are not implemented yet because of other important features T.T

> Input Data Format: It would be better to add explanation of each format. Maybe using question marks or external links.

Added question mark :D

**Review by jinevening — APPROVED** [review]
LGTM Thank you very much

**Review by YongseopKim — APPROVED** [review]
LGTM 👍

**Review by jyoungyun — APPROVED** [review]
LGTM

**Comment by hyunsik-yoon** [comment]
(optional for future) 
0. GUI shows description and cfg shows arg.
- e.g. `quantization config file` in GUI changes `quant_config` in cfg. I was thinking that what if we mention (`quantization config file (--quant_config)` in GUI.

2. The word `input` may mean two things to users: `input model` or `input data`. I hope we use  `input model` or `input data` instead of `input`.

**Pull request merged**
