### PR TITLE
[OneExplorer] Add run icon inline

### PR DESCRIPTION
**Pull request by dayo09**
This commit adds run icon for each `cfg` inline.

ONE-vscode-DCO-1.0-Signed-off-by: dayo09 <dayoung.lee@samsung.com>

### CODE REVIEW

**Comment by dayo09** [comment]
0630-run-icon

Before: You need to right-click and `run` the cfg
After: You can click on the `play` icon inline on the cfg.

- When you hover over the icon, the name `Run with the toolchain` shows up.

**Review by yunjayh — APPROVED** [review]
LGTM

**Review by jyoungyun — APPROVED** [review]
LGTM

This icon is not available if the toolchain is not installed.

**Comment by hyunsik-yoon** [comment]
Icon is cute. :-)

> This icon is not available if the toolchain is not installed.

@dayo09,
What happens when user clicks this icon when no toolchain is installed?

**Comment by dayo09** [comment]
@jyoungyun @hyunsik-yoon The icon only plays the same with the current `run` command.

**Comment by dayo09** [comment]
@hyunsik-yoon @jyoungyun 

I have updated the OneExplorer backlog.

> - [ ] Decide behavior when toolchain is not installed
https://github.com/Samsung/ONE-vscode/issues/695#issue-1244480477

**Pull request merged**
