### PR TITLE
[CircleGraph/test] Initial test for CircleGraphCtrl

### PR DESCRIPTION
**Pull request by seanshpark**
This will introduce initial unit test for CircleGraphCtrl class.

ONE-vscode-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
from #966

**Review by hyunsik-yoon — APPROVED** [review]

**Comment by llFreetimell** [comment]
Nowadays, we are too hard to create so many negative TCs.
So I was thinking following things
- Integrating some positive TCs which are just copy & pasted test codes.
- Excluding source codes from TC analysis which are too hard to validate by TCs because of UI, message communication, etc.

I am checking second option for now.
If second option is accepted, this PR can be closed.
Otherwise, I will ask you to integrate positive TCs into one.

Please wait a moment :)

**Comment by llFreetimell** [comment]
Since #1082 is merged, could you determine whether this PR will be closed or we may go as it is? :)

I am not against with merging this PR. Actually many TC is always right :D
But just worried about "Can negative TC be created...?"

**Comment by seanshpark** [comment]
> could you determine whether this PR will be closed or we may go as it is? :)

I'll check with test coverage :)

**Pull request closed without merging**
