### PR TITLE
[Backend] Introduce Toolchain class

### PR DESCRIPTION
**Pull request by YongseopKim**
Let's introduce Toolchain class.

ONE-vscode-DCO-1.0-Signed-off-by: Yongseop Kim <<yons.kim@samsung.com>>

### CODE REVIEW

**Review by jyoungyun — COMMENTED** [review]
I will wait for #490, #489 PR to be merged.

**Comment by hyunsik-yoon** [comment]
@jyoungyun 
I guess that @YongseopKim's intention is to remove comment ourselves when we need  this interface while he is out-of-office.

**Review by hyunsik-yoon — APPROVED** [review]

**Comment by YongseopKim** [comment]
Yes, @hyunsik-yoon 's saying is my intention :-)
Now Comment and Version class are merged so I'll introduce with uncommented class.

**Comment by YongseopKim** [comment]
https://github.com/Samsung/ONE-vscode/pull/499 is necessary.

**Review by hyunsik-yoon — DISMISSED** [review]
Thanks @YongseopKim. 👍

**Review by jyoungyun — DISMISSED** [review]
LGTM, Thank you :)

**Comment by YongseopKim** [comment]
Okay, it is ready now.

**Comment by YongseopKim** [comment]
PTAL again.

**Review by hyunsik-yoon — APPROVED** [review]

**Comment by YongseopKim** [comment]
PTAL @jyoungyun

**Review by jyoungyun — APPROVED** [review]
LGTM

**Pull request merged**
