### PR TITLE
[Unittest] Mark a test target glob

### PR DESCRIPTION
**Pull request by dayo09**
This commit add comment to a test target glob
to make it easy to notice.

ONE-vscode-DCO-1.0-Signed-off-by: Dayoung Lee <dayoung.lee@samsung.com>

---

Let's support a test target list or something later.

### CODE REVIEW

**Comment by YongseopKim** [comment]
@dayo09 can I ask why you do this?

```ts
export function run(): Promise<void> {
  // fgrep: 'str' if we need to filter
  const mocha = new Mocha({ui: 'tdd', color: true});
```

It's because I think a kind of `grep` features can support it.

**Comment by dayo09** [comment]
@[YongseopKim](https://github.com/YongseopKim) May I ask how to use the feature?

**Comment by YongseopKim** [comment]
```ts
    // NOTE
    //
    // When you want a selective local unittest,
    // Edit '**/**.test.js' into your desired glob expression
    //
    // EXAMPLE
    //
    // To test only src/Tests/OneExplorer/ConfigObject.test.js,
    // '**/ConfigObject.test.js'
```

===>

For example, if you want to run the only tests - the suite `Backend`,
```ts
// src/Tests/Backend/Backend.test.ts
suite('Backend', function() {
  suite('backendRegistrationApi', function() {
    test('registers a backend', function() {
```

You can change it
```ts
export function run(): Promise<void> {
  // fgrep: 'str' if we need to filter
  const mocha = new Mocha({ui: 'tdd', color: true, fgrep: 'Backend'});
```

(Of course, pass options on cli rather than fixing source code. 😄

**Comment by dayo09** [comment]
@YongseopKim Oh, I didn't know that fgrep meant it. So `// fgrep: 'str' if we need to filter` this line mean it. I want to add an option but I'd rather add the comment here, I have no time for it. 

The current comment says 'str' so I didn't know the meaning. We can just improve the comment.

**Comment by YongseopKim** [comment]
@dayo09 so, what's your conclusion? to fix code? update comments? or close this?

**Comment by dayo09** [comment]
[YongseopKim](https://github.com/YongseopKim) I have updated the commit :-D

**Review by YongseopKim — APPROVED** [review]
Sorry for too late. LVGTM! 👍

**Review by hyunsik-yoon — APPROVED** [review]

**Comment by YongseopKim** [comment]
ping @Samsung/one-vscode_committers

**Pull request merged**
