### PR TITLE
Move some packages into `dependencies` in package.json

### PR DESCRIPTION
**Pull request by hyunsik-yoon**
This moves some packages from `devDependencies` to `dependencies`
in pckage.json.

Parent issue: https://github.com/Samsung/ONE-vscode/issues/447 for background and solutions.

ONE-vscode-DCO-1.0-Signed-off-by: Hyun Sik Yoon <hyunsik.yoon.1024@gmail.com>

### CODE REVIEW

**Review by YongseopKim — DISMISSED** [review]
LGTM

**Comment by llFreetimell** [comment]
Could you insert following information to `package-judgment.json` ? :)

```json
    "flatbuffers@2.0.3": {
      "licenses": "Apache-2.0",
      "repository": "https://github.com/google/flatbuffers",
      "permitted": "yes"
    },
```

**Comment by hyunsik-yoon** [comment]
I will make another PR. Please start the review after then.

**Comment by hyunsik-yoon** [comment]
License checking was successful. PTAL

**Review by llFreetimell — APPROVED** [review]
LGTM

**Review by YongseopKim — APPROVED** [review]
LGTM

**Pull request merged**
