### PR TITLE
[CircleGraph/test] Initial test for CircleGraphPanel

### PR DESCRIPTION
**Pull request by seanshpark**
This will introduce initial unit test for CircleGraphPanel class.

ONE-vscode-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
from #966

**Comment by llFreetimell** [comment]
Thanks for creating tests for `CircleGraph` ! :D
But I have a question, I cannot find any `assert` in the `CircleGraph.test.ts`.
Was it intentional?

**Comment by seanshpark** [comment]
> I cannot find any assert in the CircleGraph.test.ts.
> Was it intentional?

Mostly there is no return value to test. some exist with condition.
Methods to test are mostly simple logic.
If no assert() is a problem from SE feedback (1) add dummy `assert(true)` (2) refactor later to get some return values; I'm not sure how this is possible for now.

**Comment by llFreetimell** [comment]
> If no assert() is a problem from SE feedback

Unfortunately, when I checked this with static analysis tool, it reported that there is no assertion in test code :(
But refactoring may bother you and may take some time.
So how about just adding following simple assertions for now? :)

```ts
  suite('#createOrShow', function() {
    test('createOrShow model with no error ', function() {
      // NOTE createOrShow(extensionUri, undefied) will show file open dialog
      // which test doen't execute as expected
      const panel = CircleGraphPanel.createOrShow(extensionUri, modelToLoad);
      assert.notStrictEqual(panel, undefined);
      panel?.dispose();
      const panel2 = CircleGraphPanel.createOrShow(extensionUri, modelToLoad);
      assert.notStrictEqual(panel2, undefined);
    });
  });
  suite('#isReady', function() {
    test('isReady check', function() {
      const panel = CircleGraphPanel.createOrShow(extensionUri, modelToLoad);
      assert.notStrictEqual(panel, undefined);
      assert.strictEqual(panel?.isReady(), false);
      panel?.dispose();
    });
  });
  ...
  suite('#setPartition', function() {
    test('setPartition check', function() {
      const panel = CircleGraphPanel.createOrShow(extensionUri, modelToLoad);
      assert.notStrictEqual(panel, undefined);
      panel?.setPartition({a: 'B'});
      panel?.dispose();
      assert.ok(true);
    });
  });
```

**Review by llFreetimell — APPROVED** [review]
LGTM!

**Review by hyunsik-yoon — APPROVED** [review]

**Pull request merged**
