### PR TITLE
[CI] Introduce check pr test

### PR DESCRIPTION
**Pull request by YongseopKim**
Let's introduce check-pr-test.

ONE-vscode-DCO-1.0-Signed-off-by: Yongseop Kim <yons.kim@samsung.com>

### CODE REVIEW

**Comment by YongseopKim** [comment]
https://github.com/Samsung/ONE-vscode/runs/5765023472

**Comment by YongseopKim** [comment]
PTAL @Samsung/one-vscode

**Review by hyunsik-yoon — APPROVED** [review]
LGTM

**Comment by hyunsik-yoon** [comment]
Note: xvfb: https://github.com/Samsung/ONE-vscode/pull/360#issuecomment-1068845901

**Review by llFreetimell — APPROVED** [review]
LGTM

**Pull request merged**
