### PR TITLE
[Jsontracer] Add level to render bar-graph

### PR DESCRIPTION
**Pull request by parkjisu6239**
This will render level-container. The level container will contain several bars on the bar chart.

ONE-vscode-DCO-1.0-Signed-off-by: Jisu Park <parkjisu6239@gmail.com>

### CODE REVIEW

**Comment by parkjisu6239** [comment]
from draft #126
from issue #94

**Review by wnsdud4197 — APPROVED** [review]

**Comment by parkjisu6239** [comment]
I applied a format-checker #161

**Review by llFreetimell — DISMISSED** [review]
LGTM

**Comment by llFreetimell** [comment]
@parkjisu6239 

Oops conflict... please rebase T.T

**Review by llFreetimell — DISMISSED** [review]
LGTM

**Comment by llFreetimell** [comment]
@parkjisu6239 

We may fix `dashboard.js` first and then rebase this PR T.T

**Comment by seanshpark** [comment]
To format checker results, click on `Details` and then check on `format.patch` file to download

image

If you're using Linux, run `bash infra/format`

**Comment by seanshpark** [comment]
What I see is

```diff
diff --git a/media/Jsontracer/dashboard.js b/media/Jsontracer/dashboard.js
index 606c380..db13928 100644
--- a/media/Jsontracer/dashboard.js
+++ b/media/Jsontracer/dashboard.js
@@ -50,8 +50,7 @@ import renderLevel from './level.js';
 
 export default function renderDashboard(utility, timeLimit, digit, data) {
   // TODO renderRuler(timeLimit, digit);
-  Object.keys(data).map(
-    key => {
-        renderLevel(timeLimit, key, utility[key], data[key]);
-    });
+  Object.keys(data).map(key => {
+    renderLevel(timeLimit, key, utility[key], data[key]);
+  });
 }
diff --git a/media/Jsontracer/level.js b/media/Jsontracer/level.js
index 8574865..24cf83b 100644
--- a/media/Jsontracer/level.js
+++ b/media/Jsontracer/level.js
@@ -72,7 +72,8 @@ export default function renderLevel(timeLimit, title, usage, data) {
   levelContainer.append(levelHeader);
   graph.append(levelContainer);
 
-  Object.keys(data).map(key => {
-    // TODO renderCategory(timeLimit, key, data[key]);
-  });
+  Object.keys(data).map(
+      key => {
+          // TODO renderCategory(timeLimit, key, data[key]);
+      });
 }
```

**Comment by parkjisu6239** [comment]
> If you're using Linux, run bash infra/format

Okay Thank you!

**Comment by parkjisu6239** [comment]
I will fix contents and create new PR.
I close this PR.

**Pull request closed without merging**
