### PR TITLE
[OneExplorer] Open files with default editor

### PR DESCRIPTION
**Pull request by dayo09**
This commit opens product files with default editor in One Explorer

ONE-vscode-DCO-1.0-Signed-off-by: Dayoung Lee <dayoung.lee@samsung.com>

### CODE REVIEW

**Review by jyoungyun — APPROVED** [review]
LGTM

**Comment by jyoungyun** [comment]
@dayo09 Isn't it enough 1 approval?

**Review by shs-park — APPROVED** [review]
LGTM!
=)

**Comment by dayo09** [comment]
@jyoungyun I asked for 2 approvals because it actually includes critical UI changes.

**Pull request merged**
