### PR TITLE
Add BSD-3 Clause License

### PR DESCRIPTION
**Pull request by llFreetimell**
This commit adds BSD-3 Clause License.

ONE-vscode-DCO-1.0-Signed-off-by: Seok NamKoong <seok9311@naver.com>

### CODE REVIEW

**Review by seanshpark — APPROVED** [review]

**Comment by mhs4670go** [comment]
`//` isn't needed because it is not in codes, is it?

**Review by seanshpark — APPROVED** [review]

**Review by mhs4670go — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
@lemmaa , ping

**Review by lemmaa — APPROVED** [review]
LGTM

**Pull request merged**
