### PR TITLE
[Circletracer] Add a semicolon to the types file

### PR DESCRIPTION
**Pull request by CODe1995**
Add semicolon to resolve formatchecker warning

ONE-vscode-DCO-1.0-Signed-off-by: Seunghyun Kang <code.57x53@gmail.com>

### CODE REVIEW

**Comment by yesfordev** [comment]
LGTM👍🏼

**Comment by CODe1995** [comment]
from draft #179
from issue #66.

**Review by yesfordev — APPROVED** [review]
LGTM👍🏼

**Review by donggillee-dev — APPROVED** [review]
LGTM👍

**Review by llFreetimell — APPROVED** [review]
LGTM

**Pull request merged**
