### PR TITLE
[PartEditor] Revise backend list from extension

### PR DESCRIPTION
**Pull request by seanshpark**
This will revise to fetch backend list items from extension.

ONE-vscode-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
> Could you describe a bit about the usage of 0th item (default)? Thanks.

`(default)` is the default backend assigned to, when the node is not mentioned in the list.
ex)
```
[partition]
backends=cpu,acl_cl
default=cpu
comply=opcode

[OPCODE]
ADD=acl_cl
```

in this change, `(default)` won't be shown in the ListBox.
All the nodes will have key(index) of 0 for initial value, which is `default` backend.

**Review by hyunsik-yoon — APPROVED** [review]

**Comment by seanshpark** [comment]
@hyunsik-yoon , as YOU are the ONLY one interested in this task, I would like to change to `1 approval` and move on.

**Review by dayo09 — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
@dayo09 , thanks for the review!

**Pull request merged**
