### PR TITLE
[Circletracer] Add circle flatbuffers file

### PR DESCRIPTION
**Pull request by CODe1995**
These files are automatically generated by compiling the circle
flatbuffers schema. It is used to analyze circle files.

ONE-vscode-DCO-1.0-Signed-off-by: Seunghyun Kang <code.57x53@gmail.com>

### CODE REVIEW

**Comment by CODe1995** [comment]
from draft #179
from issue #66.

**Comment by CODe1995** [comment]
It seems to be a problem caused by the flatbuffers module not being included.

**Comment by llFreetimell** [comment]
I think we need two things :(

- Exclude `src/Circlereader/circle-analysis/circle/*.ts` files from format-check list
- Rebase

**Comment by CODe1995** [comment]
I've modified the code to match the format check. :)

**Review by wnsdud4197 — APPROVED** [review]

**Comment by llFreetimell** [comment]
Did you modified the file names? For example, `b-c-q-*.ts` or `*-r-n-n-*` files...?
Or FlatBuffer generated the names...?

**Comment by CODe1995** [comment]
> Did you modified the file names? For example, `b-c-q-*.ts` or `*-r-n-n-*` files...? Or FlatBuffer generated the names...?

It's automatically created 😥

**Comment by llFreetimell** [comment]
### For future (re)viewers

Usually, we recommend to create PR as small enough to review easily.
However, ts files in this PR are automatically generated by FlatBuffer compiler and they said we should not modify them.
Also, ts files in this PR are the result of compilation, not mixed items.
Therefore this PR could be merged even it includes a lot of files.

**Review by llFreetimell — APPROVED** [review]
LGTM

**Pull request merged**
