### PR TITLE
Enable js format checker

### PR DESCRIPTION
**Pull request by seanshpark**
This will enable format checker for JavaScript files in src and media.

ONE-vscode-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
For #160

**Review by llFreetimell — APPROVED** [review]
LGTM

**Review by llFreetimell — APPROVED** [review]
LGTM

**Review by mhs4670go — APPROVED** [review]
LGTM

**Pull request merged**
