### PR TITLE
[MPQEditor] Implement open and other commands

### PR DESCRIPTION
**Pull request by stamalakhov**
This commit implements open and other commands for MPQSelectionPanel.

Its correctness is tested in https://github.com/Samsung/ONE-vscode/pull/1530

Fresh draft: https://github.com/Samsung/ONE-vscode/pull/1530
Full draft: https://github.com/Samsung/ONE-vscode/pull/1505
Related: https://github.com/Samsung/ONE-vscode/issues/1491

ONE-vscode-DCO-1.0-Signed-off-by: s.malakhov <s.malakhov@partner.samsung.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
It would be better to change "other" to include actual command

`Implement open and other commands`

**Comment by stamalakhov** [comment]
> It would be better to change "other" to include actual command
> 
> `Implement open and other commands`

ok. Thank you.

**Comment by stamalakhov** [comment]
> It would be better to change "other" to include actual command
> 
> `Implement open and other commands`

@seanshpark 
done

**Review by dayo09 — APPROVED** [review]
👍

**Review by seanshpark — APPROVED** [review]
LGTM

**Pull request merged**
