### PR TITLE
Change Package Descripion

### PR DESCRIPTION
**Pull request by hyunsik-yoon**
This changes package description form "ONE Compiler for VSCode"
to "ONE for VSCode"
to synchronize comment at https://github.com/Samsung/ONE-vscode/pull/332#discussion_r824399840.

ONE-vscode-DCO-1.0-Signed-off-by: Hyun Sik Yoon <hyunsik.yoon.1024@gmail.com>

### CODE REVIEW

**Comment by hyunsik-yoon** [comment]
CI problem is being handled by @llFreetimell. 😸 
Let's wait some more time.

**Comment by llFreetimell** [comment]
Sorry for bothering T.T
Would you rebase with latest commit? :)

**Comment by hyunsik-yoon** [comment]
rebased.

**Review by llFreetimell — APPROVED** [review]
LGTM

**Review by yunjayh — APPROVED** [review]

**Review by mhs4670go — APPROVED** [review]

**Pull request merged**
