### PR TITLE
Enable PR format checker

### PR DESCRIPTION
**Pull request by seanshpark**
Add initial PR format checker.

ONE-vscode-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Review by mhs4670go — DISMISSED** [review]
LGTM

**Comment by mhs4670go** [comment]
Oh,, it runs!

**Comment by seanshpark** [comment]
> Oh,, it runs!

Made a branch in this REPO... 

I'll rebase after #33 lands

**Comment by mhs4670go** [comment]
https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

@seanshpark Maybe this is related?

**Comment by seanshpark** [comment]
> Maybe this is related?

Seems so, it's reasonable... :)

**Review by mhs4670go — APPROVED** [review]

**Review by llFreetimell — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
For history, for #20

**Pull request merged**
