### PR TITLE
Add `npm run clean`

### PR DESCRIPTION
**Pull request by YongseopKim**
Let's add npm run clean to remove output directory.

ONE-vscode-DCO-1.0-Signed-off-by: Yongseop Kim <yons.kim@samsung.com>

### CODE REVIEW

**Comment by YongseopKim** [comment]
Usage
```
$ npm run clean
```

**Comment by YongseopKim** [comment]
FYI, and now I also found out that some commands including this by introducing me are too based on linux-os. This should be fixed.

**Review by mhs4670go — APPROVED** [review]
LGTM

**Comment by mhs4670go** [comment]
> FYI, and now I also found out that some commands including this by introducing me are too based on linux-os. This should be fixed.

There is a npm package called [run-sciprt-os](https://www.npmjs.com/package/run-script-os). I think this can be applied later:)

**Comment by YongseopKim** [comment]
@mhs4670go thanks, I'll try soon! 👍

**Review by hyunsik-yoon — APPROVED** [review]

**Pull request merged**
