### PR TITLE
[Circletracer] Add a file that init builtin options

### PR DESCRIPTION
**Pull request by donggillee-dev**
Returns the builtInCodes of model.
The value returning from this function will help recognize the model type during visualization.

ONE-vscode-DCO-1.0-Signed-off-by: Donggil Lee donggillee94@gmail.com

### CODE REVIEW

**Comment by donggillee-dev** [comment]
from draft #179
from issue #66.

**Review by llFreetimell — APPROVED** [review]
LGTM

**Comment by CODe1995** [comment]
LGTM

**Review by CODe1995 — APPROVED** [review]

**Comment by yesfordev** [comment]
LGTM

**Review by yesfordev — APPROVED** [review]
LGTM👍🏼

**Comment by llFreetimell** [comment]
@donggillee-dev There is no commit msg... where is it @.@

**Comment by donggillee-dev** [comment]
> @donggillee-dev There is no commit msg... where is it @.@

I'm sorry. I forgot the message... Do I just have to put up the commitment again?

**Comment by donggillee-dev** [comment]
> @donggillee-dev There is no commit msg... where is it @.@

@llFreetimell I added a commitment message and posted it. Is this right? :)

**Review by CODe1995 — APPROVED** [review]
LGTM

**Review by yesfordev — APPROVED** [review]
LGTM!

**Review by llFreetimell — APPROVED** [review]
LGTM

**Pull request merged**
