### PR TITLE
Introduce csslint and htmlhint as dev packages

### PR DESCRIPTION
**Pull request by seanshpark**
This will introduce csslint and htmlhint as development packages and run as pretest.

ONE-vscode-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
From draft #113

**Comment by seanshpark** [comment]
`csslint` tool fails if there is no `.css` file exist in the  directory...

**Review by mhs4670go — APPROVED** [review]
LGTM

**Review by jinevening — APPROVED** [review]
LGTM

**Pull request merged**
