### PR TITLE
Show "ONE" instead of "one-vscode" in setting

### PR DESCRIPTION
**Pull request by hyunsik-yoon**
This shows "ONE" in setting. Previously it was "one-vscode".

For #311

ONE-vscode-DCO-1.0-Signed-off-by: Hyun Sik Yoon <hyunsik.yoon.1024@gmail.com>

### CODE REVIEW

**Review by YongseopKim — APPROVED** [review]
LGTM

**Review by llFreetimell — APPROVED** [review]
LGTM

**Comment by llFreetimell** [comment]
@hyunsik-yoon Shall I merge this now or wait a little bit more? :)

**Comment by hyunsik-yoon** [comment]
@llFreetimell please merge. Thanks!

**Pull request merged**
