### PR TITLE
DRAFT initial VisquvProvider

### PR DESCRIPTION
**Pull request by seanshpark**
on-going draft to provide VisquvProvider

Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
for #1350

**Comment by jyoungyun** [comment]
I'm sorry but I'm not used to this change. Could you share some files needed to view the visq viewer?

**Comment by seanshpark** [comment]
> I'm sorry but I'm not used to this change. Could you share some files needed to view the visq viewer?

issue: #1350 --> which came from https://github.com/Samsung/ONE/issues/9694

original json file: https://github.com/Samsung/ONE/pull/9868#issuecomment-1280161345

but this is some problems with infinity so I changed some.

what I used;
- you can find `mobilenet_v1_keepdims_relu6` circle file in TRIV_Setup
```json
{
  "meta": {
      "title": "Test of VISQ",
      "model": "mobilenet_v1_keepdims_relu6.0to33.circle",
      "metric": "MPEIR",
      "colorscheme": [
          {
              "b": "-Infinity",
              "e": 0.1111,
              "c": "#ffffcc"
          },
          {
              "b": 0.1111,
              "e": 0.2222,
              "c": "#ffeda0"
          },
          {
              "b": 0.2222,
              "e": 0.3333,
              "c": "#fed976"
          },
          {
              "b": 0.3333,
              "e": 0.4444,
              "c": "#feb24c"
          },
          {
              "b": 0.4444,
              "e": 0.5556,
              "c": "#fd8d3c"
          },
          {
              "b": 0.5556,
              "e": 0.6667,
              "c": "#fc4e2a"
          },
          {
              "b": 0.6667,
              "e": 0.7778,
              "c": "#e31a1c"
          },
          {
              "b": 0.7778,
              "e": 0.8889,
              "c": "#bd0026"
          },
          {
              "b": 0.8889,
              "e": "Infinity",
              "c": "#800026"
          }
      ]
  },
  "error": [
      {
          "conv_pw_2_relu/Relu6": 0.3107,
          "conv_dw_3_relu/Relu6": 0.4123,
          "conv_pw_1_relu/Relu6": 0.4148,
          "conv_pw_3_relu/Relu6": 0.3561,
          "conv_dw_13_relu/Relu6": 0.3424,
          "conv_dw_11_relu/Relu6": 0.2673,
          "conv_pad_6/Pad": 0.3413,
          "conv_pad_4/Pad": 0.3561,
          "conv_pw_5_relu/Relu6": 0.3413,
          "conv_pad_2/Pad": 0.4148,
          "conv_dw_5_relu/Relu6": 0.3664,
          "conv_dw_12_relu/Relu6": 0.2074,
          "conv_dw_10_relu/Relu6": 0.2552,
          "conv_dw_2_relu/Relu6": 0.2368,
          "conv_pw_9_relu/Relu6": 0.2879,
          "conv_preds/BiasAdd": 0.096,
          "conv_dw_7_relu/Relu6": 0.5072,
          "conv1_pad/Pad": 0.002,
          "conv_pw_10_relu/Relu6": 0.3139,
          "conv_pw_13_relu/Relu6": 0.8512,
          "conv_pw_4_relu/Relu6": 0.3238,
          "conv_dw_9_relu/Relu6": 0.2811,
          "conv_dw_8_relu/Relu6": 0.3756,
          "conv_dw_6_relu/Relu6": 0.3342,
          "conv_dw_1_relu/Relu6": 0.1459,
          "conv_dw_4_relu/Relu6": 0.3763,
          "conv1_relu/Relu6": 0.0172,
          "conv_pw_8_relu/Relu6": 0.2751,
          "conv_pw_12_relu/Relu6": 0.278,
          "conv_pw_6_relu/Relu6": 0.4567,
          "Mean": 0.238,
          "conv_pw_7_relu/Relu6": 0.3852,
          "conv_pw_11_relu/Relu6": 0.256,
          "conv_pad_12/Pad": 0.256
      }
  ]
}
```

**Comment by seanshpark** [comment]
all landed

**Pull request closed without merging**
