### PR TITLE
[Toolchain] Add set default toolchain command

### PR DESCRIPTION
**Pull request by jyoungyun**
This commit adds set default toolchain command and icon.

ONE-vscode-DCO-1.0-Signed-off-by: Jiyoung Yun <jy910.yun@samsung.com>

Draft PR: #854

### CODE REVIEW

**Comment by jyoungyun** [comment]
This icon will be shown like this:

**Comment by YongseopKim** [comment]
Is it not yet showing [the image](https://github.com/Samsung/ONE-vscode/pull/1004#issuecomment-1178856720)?

**Review by YongseopKim — APPROVED** [review]
LGTM

**Review by llFreetimell — APPROVED** [review]

**Comment by jyoungyun** [comment]
> Is it not yet showing the image?

I don't understand what you meant. You can see the check icon if there is an installed toolchain in Toolchain View.

**Comment by YongseopKim** [comment]
@jyoungyun answered offline
- The function is not implemented but it can show its icon!

**Pull request merged**
