### PR TITLE
[Backend] Uncomment Executor and ExecutorBase classes

### PR DESCRIPTION
**Pull request by YongseopKim**
Let's uncomment Executor and ExecutorBase classes.

ONE-vscode-DCO-1.0-Signed-off-by: Yongseop Kim <<yons.kim@samsung.com>>

### CODE REVIEW

**Comment by YongseopKim** [comment]
I think that `ExecutorBase::inference` can be filled by like `onecc run` or `onecc inferencer`.

**Review by hyunsik-yoon — APPROVED** [review]

**Comment by YongseopKim** [comment]
PTAL @jyoungyun

**Review by jyoungyun — APPROVED** [review]
LGTM

**Pull request merged**
