### PR TITLE
[Circletracer] Add dagre-d3 static file for visualization

### PR DESCRIPTION
**Pull request by CODe1995**
- This is a min.js file with spaces and newlines removed
- Open source for drawing node graphs in webview.

ONE-vscode-DCO-1.0-Signed-off-by: Seunghyun Kang <code.57x53@gmail.com>

### CODE REVIEW

**Comment by CODe1995** [comment]
from draft #179
from issue #66.

**Comment by CODe1995** [comment]
@llFreetimell 
This is a compressed min.js file, so it should be excluded from the formatchecker target.

**Comment by seanshpark** [comment]
I think it would be better to put to separate folder like `external` that can be excluded.
And license should be checked.

**Comment by CODe1995** [comment]
@seanshpark 
I moved the minjs file to the `ext` folder inside `media/Circletracer`. This folder will be managed separately from other static files.
In addition, all licenses related to the file have been checked and confirmed that there is no problem.

**Comment by seanshpark** [comment]
Could you please use full `external` ?
I could think `ext` as extended, extra, ...

**Comment by llFreetimell** [comment]
> all licenses related to the file have been checked and confirmed that there is no problem.

This can be checked by `npm install dagre-d3` and `npx license-checker`.

@CODe1995 

This file is exactly same with https://github.com/dagrejs/dagre-d3/blob/master/dist/dagre-d3.min.js, right?

**Comment by llFreetimell** [comment]
BTW, I should exclude `external` first and then merge this...

**Comment by CODe1995** [comment]
> This file is exactly same with https://github.com/dagrejs/dagre-d3/blob/master/dist/dagre-d3.min.js, right? Without any modification?

I used version 0.5.0 released [here](https://github.com/dagrejs/dagre-d3/releases). All contents match the original file.

**Comment by llFreetimell** [comment]
@CODe1995 

Could you create `media/Circletracer/external/.clang-format` as following?

```
# This directory includes EXTERNAL open source project files,
# which are not modified.
# So we will not fix any warnings for them.

DisableFormat: true
SortIncludes: false
```

**Comment by llFreetimell** [comment]
@CODe1995 Please rebase this PR!

**Review by llFreetimell — APPROVED** [review]
LGTM

**Review by yesfordev — APPROVED** [review]
LGTM :)

**Pull request merged**
