### PR TITLE
[media/CircleGraph] Add netron source

### PR DESCRIPTION
**Pull request by seanshpark**
This will add netron source as-is into external.

ONE-vscode-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Review by mhs4670go — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
for #520, from draft #482

**Review by hyunsik-yoon — APPROVED** [review]

**Comment by llFreetimell** [comment]
#### NO MERGE 

Waiting for review about using LICENSE and ORIGIN file.
Until then, please do not merge this PR.

**Comment by seanshpark** [comment]
@llFreetimell , how long should I wait for the review?

**Comment by llFreetimell** [comment]
I received irrelevant answer for the question from the open source department, so I asked again right after I received the message yesterday but not answering until now :(

@lemmaa Would it be okay to merge first and then fix later if some license/copyright issue is found? I think this PR is okay but I asked to open source department for assurance...

**Comment by llFreetimell** [comment]
Let's merge first and then look at it in the near future again...
(License/Copyright related changes can be applied later)

**Pull request merged**
