### PR TITLE
[Tests] Add unit tests for Nonce

### PR DESCRIPTION
**Pull request by seanshpark**
This will add unit tests for Nonce in Utils.

ONE-vscode-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Review by llFreetimell — APPROVED** [review]
LGTM

**Review by hyunsik-yoon — APPROVED** [review]

**Comment by hyunsik-yoon** [comment]
@llFreetimell I wonder if we need to test files in `external`.

**Comment by seanshpark** [comment]
will wait for confirm if no need to test `external`; but will need to excluded `external`s

**Comment by llFreetimell** [comment]
I confirmed that test is not needed for 100% external codes.
Instead, as @seanshpark said, `external`s should be excluded from coverage report :)
I will exclude soon!

**Comment by seanshpark** [comment]
closing as not needed :)

**Pull request closed without merging**
