### PR TITLE
[Project] Add callback to Invoke() of JobRunner

### PR DESCRIPTION
**Pull request by YongseopKim**
Let's Add callback to Invoke() of JobRunner.

ONE-vscode-DCO-1.0-Signed-off-by: Yongseop Kim <<yons.kim@samsung.com>>

### CODE REVIEW

**Comment by YongseopKim** [comment]
This should be tested with `onecc`.

**Review by hyunsik-yoon — APPROVED** [review]

**Comment by YongseopKim** [comment]
Now I check this works with onecc. But, it's okay to be merged after #491 is landed.

**Review by jyoungyun — APPROVED** [review]
LGTM

**Comment by YongseopKim** [comment]
PTAL again

**Review by jyoungyun — APPROVED** [review]
LGTM

**Review by hyunsik-yoon — APPROVED** [review]
LGTM

**Comment by YongseopKim** [comment]
PTAL @Samsung/one-vscode_committers

**Pull request merged**
