### PR TITLE
Add 'which' to dev dependency

### PR DESCRIPTION
**Pull request by seanshpark**
This will add 'which' package to dev dependency.

ONE-vscode-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
I think changes for `package-lock.json` has landed in previous PR...

**Comment by seanshpark** [comment]
Fro #119

**Review by jinevening — APPROVED** [review]
LGTM

**Review by mhs4670go — APPROVED** [review]
LGTM

**Pull request merged**
