### PR TITLE
[Toolchain] Combine the requests to the toolchain into ToolchainProvider

### PR DESCRIPTION
**Pull request by jyoungyun**
This commit combines the requests to the toolchain into ToolchainProvider.

ONE-vscode-DCO-1.0-Signed-off-by: Jiyoung Yun <jy910.yun@samsung.com>

### CODE REVIEW

**Comment by jyoungyun** [comment]
Please review this PR :)

**Comment by YongseopKim** [comment]
@jyoungyun I'd like to know a few things. Maybe others do too. 😃 
- Is is a reactoring task?
- or why is it necessary? (I ask because the commit message doesn't contain the reason.)
- No UI change?

**Comment by jyoungyun** [comment]
> * Is is a reactoring task?

Yes, this is a refactoring task for managing all toolchain job at toolchainProvider.
There was no main ui changes but it added several error logs like this:
```
              Logger.error(this.tag, 'Installation is failed');
              vscode.window.showErrorMessage('Installation is failed');
```

**Review by hyunsik-yoon — APPROVED** [review]

**Review by llFreetimell — APPROVED** [review]
LGTM

**Pull request merged**
