### PR TITLE
Revert "[Project] Fix add() of ToolArgs if value is undefined"

### PR DESCRIPTION
**Pull request by YongseopKim**
This reverts commit 33ecc5bf6c63d24f85244e9c91da78abc59d12e9.

ONE-vscode-DCO-1.0-Signed-off-by: Yongseop Kim <yons.kim@samsung.com>

### CODE REVIEW

**Comment by YongseopKim** [comment]
For reviewers, https://github.com/Samsung/ONE-vscode/pull/353#issuecomment-1069915982

@Samsung/one-vscode Sorry but I thought wrong. This PR should be reverted. The `add()` code helps handling the option will be pushed or not.

```ts
    // optional arguments
    args.add('--input_arrays', this.inputArrays); // inputArrays could be string or undefined
    args.add('--output_arrays', this.outputArrays);
    args.add('--input_shapes', this.inputShapes);
    args.add('--converter_version', this.converterVersion);
```

**Comment by llFreetimell** [comment]
@YongseopKim Could you rebase with latest main? Sorry for bothering T.T

**Comment by YongseopKim** [comment]
PTAL @Samsung/one-vscode

**Review by llFreetimell — APPROVED** [review]
LGTM

**Review by hyunsik-yoon — APPROVED** [review]

**Pull request merged**
