### PR TITLE
[Jsontracer] Add dashboard to render bar-graph

### PR DESCRIPTION
**Pull request by parkjisu6239**
This will render the ruler and the level.

ONE-vscode-DCO-1.0-Signed-off-by: Jisu Park <parkjisu6239@gmail.com>

### CODE REVIEW

**Comment by parkjisu6239** [comment]
from draft #126
from issue #94

**Review by llFreetimell — APPROVED** [review]
LGTM

**Review by wnsdud4197 — APPROVED** [review]

**Comment by llFreetimell** [comment]
@parkjisu6239 

Could you apply format-checker(#161) to this PR in advance? :)

**Comment by seanshpark** [comment]
> Could you apply format-checker(#161) to this PR in advance? :)

As there is a change with existing file in this PR, 
- if this lands first, I'll rebase #161
- if #161 lands first, rebase this with `main` branch

**Comment by llFreetimell** [comment]
@seanshpark 

As it's hard to expect when #161 is merged, how about

- Apply #161 in advance to future PRs and current draft PR
- Merge #161 
- Check whether there are some format violations and fix if there are

:)

**Comment by parkjisu6239** [comment]
@llFreetimell @seanshpark
 
If I add a new file, I will use the format-checker.
By the way, what should I do when modifying a file such as (e.g., index.js) that was previously merged into the main?
Can I check the format-checker only for the modified part?

**Comment by llFreetimell** [comment]
> check the format-checker only for the modified part?

It may bother you but it seems to be best for a moment :(

**Comment by parkjisu6239** [comment]
> It may bother you but it seems to be best for a moment :(

No problem!
I applied format-checker for changes in the current PR. Please check it :)

**Review by wnsdud4197 — APPROVED** [review]

**Review by llFreetimell — APPROVED** [review]
LGTM

**Pull request merged**
