### PR TITLE
[lint] Add envs and globals

### PR DESCRIPTION
**Pull request by dayo09**
This commit adds envs and globals to configurations to remove wrong errors.

NOTE

"node" in "env"  <-- Removes 'process' is undefined error
"mocha" in "env" <-- Removes 'test'/'suites' is undefined error
"Thenable" in "globals" <-- Removes 'Thenables' is undefined error. Thenable is defined in node_modules/@types/vscode
"NodeJS" in "gloabls" <-- Removes 'NodeJS' is undefined error. Ref https://github.com/Chatie/eslint-config/issues/45

ONE-vscode-DCO-1.0-Signed-off-by: dayo09 <dayoung.lee@samsung.com>

For #1253 #587

### CODE REVIEW

**Comment by dayo09** [comment]
This removes about 600 problems when "eslint:recommended" is on.

### BEFORE
✖ 701 problems (701 errors, 0 warnings)
26 errors and 0 warnings potentially fixable with the --fix option.

### AFTER
✖ 98 problems (98 errors, 0 warnings)
  26 errors and 0 warnings potentially fixable with the `--fix` option.

**Comment by dayo09** [comment]
@Samsung/one-vscode PTAL, too ! :-D

**Comment by llFreetimell** [comment]
For another reviewers...

https://eslint.org/docs/latest/user-guide/configuring/language-options#specifying-environments
https://eslint.org/docs/latest/user-guide/configuring/language-options#specifying-globals

**Review by llFreetimell — APPROVED** [review]

**Comment by dayo09** [comment]
You can track down with https://github.com/Samsung/ONE-vscode/issues/1253 https://github.com/Samsung/ONE-vscode/issues/587

**Review by jyoungyun — APPROVED** [review]
LGTM

**Pull request merged**
