### PR TITLE
[MPQEditor] Implement media for VISQ

### PR DESCRIPTION
**Pull request by stamalakhov**
This commit implements mpqeditor media changes for showing VISQ data for MPQ.

Its correctness is tested in https://github.com/Samsung/ONE-vscode/pull/1543

Fresh draft: https://github.com/Samsung/ONE-vscode/pull/1543
Full draft: https://github.com/Samsung/ONE-vscode/pull/1505
Related: https://github.com/Samsung/ONE-vscode/issues/1491

ONE-vscode-DCO-1.0-Signed-off-by: s.malakhov <s.malakhov@partner.samsung.com>

### CODE REVIEW

**Comment by dayo09** [comment]
Q. Could you add a sample visq.json file? I mean it doesn't have to be in this PR but it's just for reviewer's sake.

**Comment by stamalakhov** [comment]
> Q. Could you add a sample visq.json file? I mean it doesn't have to be in this PR but it's just for reviewer's sake.

@dayo09 
Ahh. Sorry. Added samples to the draft. Please see: https://github.com/Samsung/ONE-vscode/pull/1543#issue-1688467311

**Review by dayo09 — APPROVED** [review]
LGTM :-D

**Review by seanshpark — APPROVED** [review]
LGTM

**Pull request merged**
