### PR TITLE
Enable ts format checker with clang

### PR DESCRIPTION
**Pull request by seanshpark**
This will enable TypeScript format checker with clang.

Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
To do: find how to install `clang-format-8`

**Review by mhs4670go — APPROVED** [review]
LGTM

**Review by llFreetimell — APPROVED** [review]
LGTM

**Comment by seanshpark** [comment]
For history, for #20

**Pull request merged**
