### PR TITLE
[View] Add context and detail explorers

### PR DESCRIPTION
**Pull request by jyoungyun**
This commit adds context and detail explorers on ONE view container.
The detail explorer is collapsed at the first installed.
Once the user has changed the view state by moving, hiding the view,
the initial state will not be used again.

Signed-off-by: Jiyoung Yun <jy910.yun@samsung.com>

related issue: #476 
/cc @Samsung/one-vscode

### CODE REVIEW

**Review by struss — APPROVED** [review]
LGTM

**Comment by YongseopKim** [comment]
FYI, @dayo09 is out of office today.

**Review by YongseopKim — APPROVED** [review]
LGTM

**Comment by jyoungyun** [comment]
Please merge this PR.

**Pull request merged**
