### PR TITLE
[infra] Ignore copyright checker for external

### PR DESCRIPTION
**Pull request by seanshpark**
This will add netron folder to ingore list.

ONE-vscode-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
@llFreetimell , I'm adding this chage as netron codes don't have any copyright headers.
My plan is;
- add netron codes as-is without modification; these don't have any copyright comments
- modify some codes for our purpose

Do you have any guides for this case?

**Comment by seanshpark** [comment]
from draft #482

**Comment by llFreetimell** [comment]
> netron codes don't have any copyright headers.

They substituted with LICENSE file at the root directory(https://github.com/lutzroeder/netron/blob/main/LICENSE).
Please refer to following example in our repository.

https://github.com/Samsung/ONE-vscode/blob/3555737c5b1c83c73d4f08969f01353ed3d2bcb5/media/Circletracer/makedata.js#L17-L40

---

I recommend following steps.

- Create pure(not modified) netron source codes at `external` directory(e.g. `circlegraph/external`, `circlegraph/CircleGraph/external`) and add the `external` directory to `ignorePathList` in `infra/copyright/copyright-checker.ts`.
  - Add copyright & license statement of netron, origin at the top of the file.
- Use the source codes in `external` directory in your own other codes.
- Create non-pure(modified) netron source codes at non `external` directory **(Do not modify `external` directory source codes)**
  - Add copyright & license statement of Samsung at the top of the file.
  - Add copyright & license statement of netron, origin at the top of the file.
- Remove pure(not modified) netron source codes in `external` directory which are no more used.
- Remove `external` directory itself and remove `external` directory from `ignorePathList` in `infra/copyright/copyright-checker.ts`.

**Comment by seanshpark** [comment]
@llFreetimell , thansk for the guide :)

**Review by jyoungyun — APPROVED** [review]
LGTM

**Pull request merged**
