### PR TITLE
[OneExplorer] Open *.circle files with circleViewer

### PR DESCRIPTION
**Pull request by dayo09**
This commit opens *.circle files with circleViewer.

ONE-vscode-DCO-1.0-Signed-off-by: dayo09 <dayoung.lee@samsung.com>

------

Moved from #937

### CODE REVIEW

**Comment by dayo09** [comment]
### September Release Candidate

> Test coverage is OK.
> @hyunsik-yoon , please conclude Sep. release.
> 
> _Originally posted by @seanshpark in https://github.com/Samsung/ONE-vscode/issues/937#issuecomment-1195145997_

**Comment by hyunsik-yoon** [comment]
@seanshpark 
I left a question at https://github.com/Samsung/ONE-vscode/pull/937#issuecomment-1203590102. Could you write answer here? Thanks.

**Comment by seanshpark** [comment]
it's `conclude` for conclusion, decision :)

**Comment by dayo09** [comment]
So can I understand it as to be included in September Release..?

**Comment by dayo09** [comment]
> If you agree, I guess that @dayo09 could work on this PR and include CircleViewer into Sep. release (which is actually packaged on Aug 9).
> 
> _Originally posted by @hyunsik-yoon in https://github.com/Samsung/ONE-vscode/issues/937#issuecomment-1203590102_
> 

Oh it seems that you meant to include this i September release which we plan to freeze in October...
Then, may I activate this PR now?

**Review by seanshpark — APPROVED** [review]
LGTM thank you!

**Comment by dayo09** [comment]
@hyunsik-yoon said that it's far tricky to omit CircleViewer sources from our release, so it's better to include this for the upcoming release.

To add my opinion: I agree, and also think that as the most of the CircleViewer codes are excluded from test coverage, it will not affect test coverage scores critically. (it does a little, still)

Let's enable CircleViewer by OneExplorer.

**Review by hyunsik-yoon — APPROVED** [review]

**Pull request merged**
