### PR TITLE
Remove code related to `one.backend.infer`

### PR DESCRIPTION
**Pull request by hyunsik-yoon**
This removes code relate to `one.backend.infer`, which was
introduced for previous release to check feasibility.

From #1118

ONE-vscode-DCO-1.0-Signed-off-by: Hyun Sik Yoon <hyunsik.yoon.1024@gmail.com>

### CODE REVIEW

**Comment by hyunsik-yoon** [comment]
@struss Could you take a look at this PR? I added you as a reviewer since you're working source code in Executor.

**Comment by struss** [comment]
> @struss Could you take a look at this PR? I added you as a reviewer since you're working source code in Executor.

I think this removal will make TEM and TCM more nice. also, as `one-infer` adopted on `samsung/one`, I also think `one.backend.infer` will no longer needed.

so, I agree with this change.

**Review by struss — APPROVED** [review]
LGTM

**Review by llFreetimell — APPROVED** [review]
LGTM

**Pull request merged**
