### PR TITLE
[Backend] Exchange the file names: API, Backend

### PR DESCRIPTION
**Pull request by dayo09**
This commit exchagnes the file names of
Backend/API.ts and Backend/Backend.ts

ONE-vscode-DCO-1.0-Signed-off-by: dayo09 <dayoung.lee@samsung.com>

----

From #1049

### CODE REVIEW

**Comment by dayo09** [comment]
NOTE: The current commit runs the toolchain well with the current backend extension.

**Comment by hyunsik-yoon** [comment]
`interface Backend` in `backend.ts` seems good to me.
but the name `API.ts` (having `registerBackendAPI`) seems too broad. How about something like `Registration.ts`?

**Comment by dayo09** [comment]
@hyunsik-yoon I think the name is good as is. We may add other kind of APIs in the future. We may leave it as APIs and use it as API set of our ONE-vscode extension.

**Comment by hyunsik-yoon** [comment]
Related to communication between backend and one-vscode,
I think that we currently have two types of API.

- `interface Backend `
  - implemented by backend extension and called by one-vscode
- `backendRegistrationAPI`
  - implemented by one-vscode and called by backend extension 

IMHO, if you want to use file name `API.ts`, I think it would be better to put `interface Backend` into `API.ts` too since they all API.

If we want to keep two separate files,
it would be better to have more specific and consistent naming, e.g., both file name would ends with `API`. Or both file wouldn't ends with `API`.

**Comment by dayo09** [comment]
@hyunsik-yoon 

If we go with that approach, then the `Compiler.ts` and `Executor.ts` are also considered to be APIs. And I also plan to add more file like them.

I thought that most files in `Backend.ts` are those which must be implemented by backends. From the point of view, we can just leave them as is. 😃

(copied from https://github.com/Samsung/ONE-vscode/issues/1049#issuecomment-1186762154)

Or we can put them as is and `export` them from the API.ts file.

**Comment by dayo09** [comment]
@hyunsik-yoon Or, how about [this](https://github.sec.samsung.net/RS7-RuntimeNTools/ONE-vscode-TRIV/pull/92) approach?

**Comment by hyunsik-yoon** [comment]
The discussion is very confusing to me since there are two files and two times (current and future) involved.
I'd like to suggest not to use pronoun if available and use more specif terms. :-) 

Let me clarify your answer... again.

If this PR is merged, we will have the following structure:

- API.ts
  - backendRegistrationAPI
- Backend.ts
  - inteface Backend
- Compiler.ts
- ....

You mentioned,

> I think the name is good as is. We may introduce other kind(non-registration) of APIs in the future. We may leave it as APIs and use it as API set of our ONE-vscode extension.

Here, I guess you meant API.ts by _the name_.

>  I also plan to add more file like them.

I have one question here. If you want ot introduce, e.g., `File` class, I wonder where `File` would exist in the above structure. Would it be inside API.ts ? or File.ts?

**Comment by dayo09** [comment]
> Here, I guess you meant API.ts by the name.

Right :-D

> I have one question here. If you want ot introduce, e.g., File class, I wonder where File would exist in the above structure. Would it be inside API.ts ? or File.ts?

I will make a `File.ts`(for example) and make a proper api function in `API.ts`. (as you said, kinda registration functions) And if I proceed to make `BackendManager` class, I think I can wrap those API registrations somehow with BackendManager class functions.

**Comment by jyoungyun** [comment]
I like your changes. :) If you ready to merge this PR, please let me know it.

**Comment by hyunsik-yoon** [comment]
@dayo09 
I understand. Maybe we can check this name again when you finish your planned work in future but I am OK with this change. :-)

**Review by hyunsik-yoon — APPROVED** [review]

**Comment by hyunsik-yoon** [comment]
@dayo09 

> @hyunsik-yoon Furthermore, how about [this](https://github.sec.samsung.net/RS7-RuntimeNTools/ONE-vscode-TRIV/pull/92) approach?

Great. It's amazing that `package.json` has such feature. If this approach work, it would be much better to synchronize two repos. 👍

**Comment by dayo09** [comment]
@jyoungyun It's ready. PTAL :-D!

**Review by jyoungyun — APPROVED** [review]
LGTM

**Pull request merged**
