### PR TITLE
[OneExplorer] Support MondrianViewer

### PR DESCRIPTION
**Pull request by dayo09**
This commit supports MondrianViewer in OneExplorer.

### CODE REVIEW

**Comment by dayo09** [comment]
0705-mondrian

**Comment by dayo09** [comment]
### GIF

This is how it's drafted so far:

    1. Show mondrian and log files under the directory. (Cannot find a parent tflite file)

    2. Provide a `hide` toggle button


(I have changed the modelfile icon to make it notified more than so-called `extra files`)

0705-mondrian

**Comment by hyunsik-yoon** [comment]
In future, when someone wants to add a file type into one explorer,
maybe there could be some API, for example,
```
registerFile({ endsWith: "tracealloc.json", icon: "graph-scatter", { openType: "custom", customName: "'onevscode.mondrianViewer'" } ...  });
```
I think it would be very convenient.

**Comment by dayo09** [comment]
@hyunsik-yoon Thanks for the suggestion :-D

**Comment by dayo09** [comment]
All merged :-D

**Pull request closed without merging**
