### PR TITLE
Sort package.json

### PR DESCRIPTION
**Pull request by seanshpark**
This will sort item 'ini' in package.json.

Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Review by mhs4670go — APPROVED** [review]
LGTM

**Comment by mhs4670go** [comment]
@seanshpark @llFreetimell is off today. You can remove him for the review list.

**Comment by seanshpark** [comment]
> You can remove him for the review list.

This repo requires 2 reviews :)

**Review by jinevening — APPROVED** [review]
LGTM

**Pull request merged**
