### PR TITLE
[Toolchain] Change toolchain icon

### PR DESCRIPTION
**Pull request by jyoungyun**
This commit changes toolchain icon.

ONE-vscode-DCO-1.0-Signed-off-by: Jiyoung Yun <jy910.yun@samsung.com>

Draft PR: #854

### CODE REVIEW

**Comment by jyoungyun** [comment]
How about changing the toolchain icon like this?

| Before | After |
|--------|-------|
|  |  |

After introducing default toolchain, the default toolchain icon will be:


I'm looking for icon [here](https://code.visualstudio.com/api/references/icons-in-labels). Please let me know if there's a more appropriate icon for toolchain.

**Review by YongseopKim — APPROVED** [review]
LGTM 👍

**Review by llFreetimell — DISMISSED** [review]

**Comment by llFreetimell** [comment]
@jyoungyun Conflict :(

**Comment by jyoungyun** [comment]
@YongseopKim @llFreetimell PTAL again. :)

**Review by YongseopKim — APPROVED** [review]

**Review by llFreetimell — APPROVED** [review]
LGTM

**Pull request merged**
