### PR TITLE
Add command for visualization by barchart

### PR DESCRIPTION
**Pull request by wnsdud4197**
This will and command for visualization by barchart.
ONE-vscode-DCO-1.0-Signed-off-by: wnsdud4197 <wnsdud4197@naver.com>

### CODE REVIEW

**Review by parkjisu6239 — APPROVED** [review]
LGTM

**Review by llFreetimell — APPROVED** [review]
LGTM

**Comment by llFreetimell** [comment]
@seanshpark 

I added as reviewer because `package.json` file is shared for all items :)

**Comment by llFreetimell** [comment]
Oops... I found that there are two files

**Review by yesfordev — APPROVED** [review]
LGTM

**Review by seanshpark — APPROVED** [review]
LGTM

**Review by mhs4670go — APPROVED** [review]
LGTM

**Review by donggillee-dev — APPROVED** [review]
LGTM

**Pull request merged**
