### PR TITLE
Ignore eslint for CircleGraph/external

### PR DESCRIPTION
**Pull request by seanshpark**
This will include to ignore external netron codes to come.

ONE-vscode-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
from draft #517

**Review by hyunsik-yoon — APPROVED** [review]

**Comment by seanshpark** [comment]
I've updated to folder from `CircleGraph/netron` to `CircleGraph/external`

**Review by hyunsik-yoon — APPROVED** [review]

**Comment by seanshpark** [comment]
@mhs4670go PTAL

**Review by mhs4670go — APPROVED** [review]
LGTM

**Pull request merged**
