### PR TITLE
[Circlereader] Add missing copyright statement

### PR DESCRIPTION
**Pull request by llFreetimell**
This commit adds missing copyright statement to `circle-analysis/circle/*.ts` files.

ONE-vscode-DCO-1.0-Signed-off-by: Seok NamKoong <seok9311@naver.com>

---

Originated from : #298

### CODE REVIEW

**Comment by llFreetimell** [comment]
For reviewers, these files are generated at 2021 :)

**Review by YongseopKim — APPROVED** [review]
LGTM

**Review by yunjayh — APPROVED** [review]
LGTM :smile: (DId we discuss about the number of reviews to merge before?)

**Comment by llFreetimell** [comment]
> DId we discuss about the number of reviews to merge before?

Not yet discussed officially so I am following existing ground rule for now :D

**Pull request merged**
