### PR TITLE
[OneExplorer] Add 'Open with Text Editor' command

### PR DESCRIPTION
**Pull request by dayo09**
This commit adds 'open with text editor' command for cfg files.

ONE-vscode-DCO-1.0-Signed-off-by: Dayoung Lee <dayoung.lee@samsung.com>

----

From #730

### CODE REVIEW

**Comment by dayo09** [comment]
### GIF

Please find the gif [here](https://github.sec.samsung.net/RS7-RuntimeNTools/secret/issues/187#issuecomment-1525558)

**Comment by hyunsik-yoon** [comment]
@llFreetimell Could you take a look? (I guess you have plan to add text editing feature into the cfg editor)

**Comment by llFreetimell** [comment]
My feature planned was "switching text/GUI editor", so I think this feature is not that related with mine :D

**Review by llFreetimell — APPROVED** [review]
LGTM

**Comment by dayo09** [comment]
@Samsung/one-vscode PTAL 😄

**Review by yunjayh — APPROVED** [review]
The code itself looks good to me. :D 

Q) Is there a sort key option for listing candidates on right click? If there it is, it'd be better to move some functions upper, such as `Run` or `value-test` in the future.

**Comment by dayo09** [comment]
> Q) Is there a sort key option for listing candidates on right click?

Yes, sort of. We can define our commands into different groups and list them with a predefined order.

**Pull request merged**
