### PR TITLE
[media/CircleGraph] Apply visq value and color

### PR DESCRIPTION
**Pull request by seanshpark**
This will apply visq quantization error value in node and color value according to the error value.

ONE-vscode-DCO-1.0-Signed-off-by: SaeHie Park <saehie.park@gmail.com>

### CODE REVIEW

**Comment by seanshpark** [comment]
for #1350, from #1351

**Comment by seanshpark** [comment]
this change will apply node name and colors like in https://github.com/Samsung/ONE-vscode/issues/1350#issuecomment-1278612881

**Review by jyoungyun — APPROVED** [review]
LGTM

**Review by mhs4670go — APPROVED** [review]
LGTM

**Pull request merged**
