### PR TITLE
Add license statements

### PR DESCRIPTION
**Pull request by llFreetimell**
This commit adds full license statements of following opensources.
- netron (MIT)
- dagre-d3 (MIT)

ONE-vscode-DCO-1.0-Signed-off-by: Seok NamKoong <seok9311@naver.com>

### CODE REVIEW

**Review by seanshpark — APPROVED** [review]
LGTM

**Comment by mhs4670go** [comment]
MIT license statement already exists. Just adding repo URL and copyright isn't enough?

**Comment by llFreetimell** [comment]
@mhs4670go 

It may be enough but full statements can be little bit different for each open source project.
So I think it would be little bit more safe to copy&paste original full statements :)

**Review by mhs4670go — APPROVED** [review]
LGTM

**Comment by glistening** [comment]
Please proceed review and merge without my approvals or information I've written comment just for confirming the style of `LICENSE`.

But I've got answered. But the answer makes me more confused. Please find the answer in SOSHUB Q&A asked by me.

In addition, with further investigation in `LICENSE`, I don't know why it mentions `netron` and `catapult`. I am not fully aware about the implementation and dependencies of this repo.

**Comment by lemmaa** [comment]
https://github.com/Samsung/ONE-vscode/pull/251#issuecomment-940894420
> In addition, I am not sure why `LICENSE` has `netron` while I don't find any source or dependencies to them.

Same to me. Could you please explain about this? :)

**Comment by llFreetimell** [comment]
@lemmaa @glistening 

I will only add copyright to existing statement :)

---

> In addition, I am not sure why LICENSE has netron while I don't find any source or dependencies to them.

CircleTracer referenced the result of netron, so I added it :)

**Review by lemmaa — APPROVED** [review]

**Comment by llFreetimell** [comment]
This PR is too old, I will create new PR with checking additional things.
Close!

**Pull request closed without merging**
