### PR TITLE
[Circletracer] Add a file that parses node input

### PR DESCRIPTION
**Pull request by CODe1995**
Returns the inputsArray of each operator separated by name, type, and edge.
This function is used to represent the inputs data during visualization.

ONE-vscode-DCO-1.0-Signed-off-by: Seunghyun Kang <code.57x53@gmail.com>

### CODE REVIEW

**Comment by CODe1995** [comment]
from draft #179
from issue #66.

**Comment by llFreetimell** [comment]
@CODe1995 

Not related with this PR but... could you remove warnings in "Unchanged files with check annotations"?
You can check it by clicking "File changed" and see bottom.

**Comment by llFreetimell** [comment]
And please remove warnings in this PR either :)

**Comment by CODe1995** [comment]
@llFreetimell

Done. Thank you :)

**Review by donggillee-dev — APPROVED** [review]
LGTM👍

**Comment by llFreetimell** [comment]
@CODe1995 

Ah... I mean that "please create another PR to remove warnings in other files" ..!
Multiple purpose should be separated :D

**Comment by CODe1995** [comment]
> @CODe1995
> 
> Ah... I mean that "please create another PR to remove warnings in other files" ..! Multiple purpose should be separated :D

thank you. I have created a PR here(#215).

**Review by llFreetimell — APPROVED** [review]
LGTM

**Review by yesfordev — APPROVED** [review]
LGTM!

**Review by donggillee-dev — APPROVED** [review]
LGTM👍

**Review by llFreetimell — APPROVED** [review]
LGTM

**Pull request merged**
